"""adding creation timestamp to keys

Revision ID: 1dcc11fe8e60
Revises: 2561089bf1d3
Create Date: 2024-08-20 20:07:44.646576+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dcc11fe8e60'
down_revision: Union[str, None] = '2561089bf1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_keys', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_keys', 'created')
    # ### end Alembic commands ###
