"""Add owner on job_def

Revision ID: 2e883f33eae9
Revises: c5ee0dfdaaf4
Create Date: 2025-01-06 14:36:36.032104+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e883f33eae9'
down_revision: Union[str, None] = 'c5ee0dfdaaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_defs', sa.Column('owner_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.create_foreign_key(None, 'job_defs', 'profiles', ['owner_seq'], ['profile_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_defs', type_='foreignkey')
    op.drop_column('job_defs', 'owner_seq')
    # ### end Alembic commands ###
