"""Add Tag metadata

Revision ID: 981d79320d84
Revises: 23ee0bbb9213
Create Date: 2025-02-07 12:14:31.251349+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '981d79320d84'
down_revision: Union[str, None] = '23ee0bbb9213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_version_entry_points_src_file_seq_fkey', 'asset_version_entry_points', type_='foreignkey')
    op.add_column('tags', sa.Column('page_priority', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('contents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'contents')
    op.drop_column('tags', 'page_priority')
    op.create_foreign_key('asset_version_entry_points_src_file_seq_fkey', 'asset_version_entry_points', 'files', ['src_file_seq'], ['file_seq'])
    # ### end Alembic commands ###
