"""Add purpose to files

Revision ID: 984caff4b6ea
Revises: e7d827337f91
Create Date: 2024-10-21 18:16:41.109253+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '984caff4b6ea'
down_revision: Union[str, None] = 'e7d827337f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'purpose')
    # ### end Alembic commands ###
