"""create file-to-tags table


Revision ID: ab1147c07597
Revises: e7d827337f91
Create Date: 2024-10-18 11:59:28.591878+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab1147c07597'
down_revision: Union[str, None] = 'e7d827337f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_tags',
    sa.Column('type_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('type_seq', 'tag_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_tags')
    # ### end Alembic commands ###
