"""unique constraint

Revision ID: e09bddf061f9
Revises: c2727ee65170
Create Date: 2024-09-05 22:26:07.382449+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e09bddf061f9'
down_revision: Union[str, None] = 'c2727ee65170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'job_results', ['job_result_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_results', type_='unique')
    # ### end Alembic commands ###
