apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    # Add a block for Tailscale domains
    ts.net {
        errors
        cache 30
        forward . tailscale-router.tailscale.svc.cluster.local
    cache 30
      errors
    }
    .:53 {
      errors
      health {
        lameduck 5s
      }
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      prometheus :9153
      forward . /etc/resolv.conf  # Forward non-Tailscale domains to VPC DNS
      cache 30
      loop
      reload
      loadbalance
    }