name: automation

#
# This docker compose creates a testing environment for automation tier services. 
#
services:
  packager:
    container_name: packager
    image: mythica-packager:latest
    networks:
      - web
      - storage
    environment:
      MYTHICA_ENVIRONMENT: debug
      DISCORD_INFRA_ALERTS_WEBHOOK: localhost
      MYTHICA_ENDPOINT: http://localhost:5555
      MYTHICA_API_KEY: ${MYTHICA_API_KEY}
      API_BASE_URI: http://localhost:5555/v1
      TELEMETRY_ENABLE: True
      TELEMETRY_ENDPOINT: otel-sidecar:4317
      TELEMETRY_INSECURE: True
  imagemagick:
    container_name: imagemagick
    image: mythica-auto-imagemagick:latest
    networks:
      - web
      - storage
    environment:
      MYTHICA_ENVIRONMENT: debug
      DISCORD_INFRA_ALERTS_WEBHOOK: localhost
      MYTHICA_ENDPOINT: http://app:5555
      API_BASE_URI: http://app:5555/v1
      MYTHICA_API_KEY: ${MYTHICA_API_KEY}
      TELEMETRY_ENABLE: True
      TELEMETRY_ENDPOINT: otel-sidecar:4317
      TELEMETRY_INSECURE: True
  houdini-worker:
    container_name: houdini
    image: mythica-auto-houdini:latest
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks:
      - web
      - storage
    environment:
      TELEMETRY_ENABLE: False
      NATS_ENDPOINT: nats://host.docker.internal:4222
      MYTHICA_ENVIRONMENT: debug
      DISCORD_INFRA_ALERTS_WEBHOOK: localhost
      API_BASE_URI: http://host.docker.internal:8080/v1
      SFX_CLIENT_ID: ${SFX_CLIENT_ID}
      SFX_CLIENT_SECRET: ${SFX_CLIENT_SECRET}
      TELEMETRY_ENDPOINT: otel-sidecar:4317
      TELEMETRY_INSECURE: True
  blender-worker:
    container_name: blender
    image: mythica-auto-blender:latest
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks:
      - web
      - storage
    environment:
      TELEMETRY_ENABLE: False
      NATS_ENDPOINT: nats://host.docker.internal:4222
      MYTHICA_ENVIRONMENT: debug
      DISCORD_INFRA_ALERTS_WEBHOOK: localhost
      API_BASE_URI: http://host.docker.internal:8080/v1
      TELEMETRY_ENDPOINT: otel-sidecar:4317
      TELEMETRY_INSECURE: True
  workflow-worker:
    container_name: workflow
    image: mythica-auto-workflow:latest
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    networks:
      - web
      - storage
    environment:
      TELEMETRY_ENABLE: False
      NATS_ENDPOINT: nats://host.docker.internal:4222
      MYTHICA_ENVIRONMENT: debug
      DISCORD_INFRA_ALERTS_WEBHOOK: localhost
      API_BASE_URI: http://host.docker.internal:8080/v1
      TELEMETRY_ENDPOINT: otel-sidecar:4317
      TELEMETRY_INSECURE: True
networks:
  storage:
    driver: bridge
    name: storage
    external: true
  web:
    driver: bridge
    name: web
    external: true
