name: automation

#
# This docker compose creates a testing environment for automation tier services. 
#
services:
  packager:
    container_name: packager
    image: mythica-packager:latest
    networks:
      - web
      - storage
  houdini-worker:
    container_name: houdini
    image: mythica-auto-houdini:latest
    networks:
      - web
      - storage
    environment:
      MYTHICA_ENVIRONMENT: debug
      SFX_CLIENT_ID: ${SFX_CLIENT_ID}
      SFX_CLIENT_SECRET: ${SFX_CLIENT_SECRET}
networks:
  storage:
    driver: bridge
    name: storage
    external: true
  web:
    driver: bridge
    name: web
    external: true
