// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Provides a grouping for asset graphs
// Table name: topologies
export interface Topology {
    topology_seq: number;
    owner_seq: number;
    org_seq: number;
    created: string;
    updated: string;
    name: string;
    description: string;
    edge_data_schema: object;
}
// Records relationships between assets
// Table name: asset_refs
export interface AssetRef {
    topology_seq: number;
    src_id: string;
    dst_id: string;
    edge_data: object;
}
