apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-access
  namespace: web
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]