apiVersion: v1
kind: Service
metadata:
  name: mythica-fe
  namespace: web
  labels:
    app: mythica-fe
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mythica-fe
