{{- $componentContext := .Values.api.canary -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentContext.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $componentContext.replicas | default 1 }}
  strategy:
    {{- include "api.rolloutStrategy" $componentContext | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $componentContext.name }}
  template:
    metadata:
      labels:
        {{- include "api.commonLabels" . | nindent 8 }}
        {{- include "api.componentLabels" $componentContext | nindent 8 }}
    spec:
      {{- include "api.nodeSelector" $componentContext | nindent 6 }}
      terminationGracePeriodSeconds: {{ $componentContext.terminationGracePeriodSeconds }}
      serviceAccountName: api
      containers:
        - name: canary
          image: {{ include "api.image" (list . "mythica-job-canary") }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SERVICE_ENDPOINT
              value: http://app/v1
            - name: APP_VERSION
              value: {{ include "api.imageVersion" (list . "mythica-job-canary") }}
            - name: MYTHICA_LOCATION
              value: "{{ .Values.MYTHICA_LOCATION }}"
            - name: K8S_CLUSTER_NAME
              value: "{{ .Values.K8S_CLUSTER_NAME }}"

            - name: MYTHICA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: canary-secrets
                  key: MYTHICA_API_KEY

      restartPolicy: Always
