{{- $componentContext := .Values.api.webFront -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentContext.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $componentContext.replicas | default 1 }}
  strategy:
    {{- include "api.rolloutStrategy" $componentContext | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $componentContext.name }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
        {{- include "api.componentLabels" $componentContext | nindent 8 }}
    spec:
      {{- include "api.nodeSelector" $componentContext | nindent 6 }}
      securityContext:
        fsGroup: 101 # use the nginx group for file-system security privileges
      terminationGracePeriodSeconds: {{ $componentContext.terminationGracePeriodSeconds }}
      serviceAccountName: api
      initContainers:
        - name: mythica-sites-build
          image: {{ include "api.image" (list . "mythica-sites-build") }}
          imagePullPolicy: Always
          env:
            - name: PUBLISH_PATH
              value: /publish
            - name: VITE_API_BASE_URL
              value: {{ .Values.apiBaseUrl }}
            - name: VITE_IMAGES_BASE_URL
              value: {{ .Values.imagesBaseUrl}}
            - name: VITE_AUTH0_DOMAIN
              value: {{ .Values.auth0.domain}}
            - name: VITE_AUTH0_CLIENT_ID
              value: {{ .Values.auth0.clientId }}
            - name: VITE_AUTH0_AUDIENCE
              value: {{ .Values.auth0.audience }}
            - name: VITE_AUTH0_REDIRECT_URL
              value: {{ .Values.auth0.redirectUrl }}
            - name: VITE_SITE_IMAGE_VERSION
              value: {{ include "api.imageVersion" (list . "mythica-sites-build") }}
            - name: VITE_APP_IMAGE_VERSION
              value: {{ include "api.imageVersion" (list . "mythica-app") }}
            - name: VITE_MYTHICA_ENVIRONMENT
              value: {{ .Values.release }}
            - name: VITE_AWFUL_WORKERS
              value: houdini,blender,workflow
            - name: VITE_AWFUL_SCRIPT_PATH
              value: /mythica/script
            - name: VITE_AWFUL_SCRIPT_INTERFACE_PATH
              value: /mythica/script/interface
            - name: VITE_AWFUL_REST_URL
              value: http://localhost:8080/v1/automation/run
            - name: VITE_SCENE_TALK_URL
              value: wss://scenetalk.mythica.gg/ws
          volumeMounts:
            - name: dist-publish
              mountPath: "/publish"
      containers:
        - name: nginx
          image: {{ include "api.image" (list . "mythica-web-front") }}
          args: [ "nginx" ]
          imagePullPolicy: Always
          env:
            - name: CONF_FILE
              value: {{ $componentContext.nginxConfig }}
            - name: API_ENDPOINT
              value: api.app:5555
            - name: DEX_ENDPOINT
              value: dex.dex:5556
            - name: EXTERNAL_IP
              value: 35.190.85.177
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: dist-publish
              mountPath: /publish
              readOnly: true
      volumes:
        - name: dist-publish  # ephemeral volume, hosting the dist content
          emptyDir: { }
      restartPolicy: Always
