{{- $componentContext := .Values.api.letsEncrypt -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentContext.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    {{- include "api.rolloutStrategy" $componentContext | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $componentContext.name }}
  template:
    metadata:
      labels:
        {{- include "api.commonLabels" . | nindent 8 }}
        {{- include "api.componentLabels" $componentContext | nindent 8 }}
    spec:
      {{- include "api.nodeSelector" $componentContext | nindent 6 }}
      terminationGracePeriodSeconds: {{ $componentContext.terminationGracePeriodSeconds }}
      serviceAccountName: lets-encrypt
      containers:
        - name: lets-encrypt
          image: {{ include "api.image" (list . "lets-encrypt") }}
          imagePullPolicy: Always
          env:
            - name: DOMAINS
              value: "{{ join "," .Values.domains }}"
            - name: SECRET_NAME
              value: {{ $componentContext.secretName }}
          volumeMounts:
            - name: lets-encrypt-storage
              mountPath: /etc/letsencrypt
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
      volumes:
        # Nodal ephemeral volume used by the CSI driver
        - name: lets-encrypt-storage
          persistentVolumeClaim:
            claimName: lets-encrypt
      restartPolicy: Always
