{{- $componentContext := .Values.api.webFront -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentContext.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $componentContext.replicas | default 1 }}
  strategy:
    {{- include "api.rolloutStrategy" $componentContext | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $componentContext.name }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
        {{- include "api.componentLabels" $componentContext | nindent 8 }}
    spec:
      {{- include "api.nodeSelector" $componentContext | nindent 6 }}
      securityContext:
        fsGroup: 101 # use the nginx group for file-system security privileges
      terminationGracePeriodSeconds: {{ $componentContext.terminationGracePeriodSeconds }}
      serviceAccountName: api
      initContainers:
        - name: jungle3-build
          image: "{{ .Values.imageRepository }}/mythica-jungle3-build:{{ $componentContext.tag }}"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args:
            - cp -R /dist/jungle3 /dist-publish/jungle3
          volumeMounts:
            - name: dist-publish
              mountPath: "/dist-publish"
        - name: editor-build
          image: "{{ .Values.imageRepository }}/mythica-editor-build:{{ $componentContext.tag }}"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args:
            - cp -R /dist/editor /dist-publish/editor
          volumeMounts:
            - name: dist-publish
              mountPath: "/dist-publish"
      containers:
        - name: nginx
          image: "{{ .Values.imageRepository }}/mythica-web-front:{{ $componentContext.tag }}"
          args: [ "nginx", "-c", "{{ $componentContext.nginxConfig }}" ]
          imagePullPolicy: Always
          env:
            - name: API_ENDPOINT
              value: api.app:5555
            - name: DEX_ENDPOINT
              value: dex.dex:5556
            - name: EXTERNAL_IP
              value: 35.190.85.177
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: dist-publish
              mountPath: /publish
              readOnly: true
      volumes:
        - name: dist-publish  # ephemeral volume, hosting the dist content
          emptyDir: { }
      restartPolicy: Always
