apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: front-end-api-sa@controlnet-407314.iam.gserviceaccount.com
