apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
  namespace: api
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 10
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
        tier: web
        version: "1.0"
        release: production
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Scale-Out"
      securityContext:
        fsGroup: 101 # use the nginx group for file-system security privileges
      terminationGracePeriodSeconds: 60
      serviceAccountName: api
      initContainers:
        - name: jungle3-build
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-jungle3-build:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dist-publish
              mountPath: "/publish"
          env:
            - name: PUBLISH_PATH
              value: /publish/jungle3
            - name: VITE_API_BASE_URL
              value: https://api.mythica.ai/v1
            - name: VITE_IMAGES_BASE_URL
              value: https://api.mythica.ai/images
            - name: VITE_AUTH0_DOMAIN
              value: dev-dtvqj0iuc5rnb6x2.us.auth0.com
            - name: VITE_AUTH0_CLIENT_ID
              value: caa07HclGxulrcv43hgGziNJx7cQ8GED
            - name: VITE_AUTH0_AUDIENCE
              value: https://api.mythica.ai/v1
            - name: VITE_AUTH0_REDIRECT_URL
              value: https://api.mythica.ai

      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-web-front:v1.0.1
          args: [ "nginx", "-c", "/etc/nginx/nginx-gke.conf" ]
          imagePullPolicy: Always
          env:
            - name: API_ENDPOINT
              value: api.app:5555
            - name: DEX_ENDPOINT
              value: dex.dex:5556
            - name: EXTERNAL_IP
              value: 35.190.85.177
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: dist-publish
              mountPath: /publish
              readOnly: true
            - name: letsencrypt-tls
              mountPath: "/etc/nginx/tls"
              readOnly: true
      volumes:
        - name: dist-publish  # ephemeral volume, hosting the dist content
          emptyDir: { }
        - name: letsencrypt-tls
          secret:
            secretName: letsencrypt-tls
            defaultMode: 0640
      restartPolicy: Always
