apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
  namespace: api
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 10
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
        tier: web
        version: "1.0"
        release: production
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Scale-Out"
      securityContext:
        fsGroup: 101 # use the nginx group for file-system security privileges
      terminationGracePeriodSeconds: 60
      serviceAccountName: api
      initContainers:
        - name: publish-init
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-web-publish-init:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: ephemeral-sites-volume
              mountPath: /sites
          env:
            - name: PUBLISH_PATH
              value: "/sites"
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-web-front:latest
          args: [ "nginx", "-c", "/etc/nginx/nginx-gke.conf" ]
          imagePullPolicy: Always
          env:
            - name: API_ENDPOINT
              value: api.app:5555
            - name: DEX_ENDPOINT
              value: dex:5556
            - name: EXTERNAL_IP
              value: 35.190.85.177
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: ephemeral-sites-volume
              mountPath: /sites
            - name: letsencrypt-tls
              mountPath: "/etc/nginx/tls"
              readOnly: true
      volumes:
        - name: ephemeral-sites-volume
          emptyDir: { }
        - name: letsencrypt-tls
          secret:
            secretName: letsencrypt-tls
            defaultMode: 0640
      restartPolicy: Always
