apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gcs-proxy
  namespace: api
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        host: images.mythica.ai
        requestPath: /_health
  targetRef:
    group: ""
    kind: Service
    name: gcs-proxy
