apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-front
  namespace: api
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_NAMED_PORT
        portName: http
        host: api.mythica.ai
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: web-front
