apiVersion: v1
kind: Service
metadata:
  name: web-front
  namespace: api
  labels:
    app: web-front
    tier: web
    version: "1.0"
    release: production
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: web-front
