#
# This docker compose creates a backend testing environment for 
# storage tier services. You can run this compose set with -d (--detach)
#
services:
  dist:
    container_name: jungle3-build
    image: mythica-jungle3-build:latest
    volumes:
      - dist:/dist
  nginx:
    container_name: nginx
    image: mythica-web-front:latest
    depends_on:
      - dist
      - app
    ports:
      - "8080:80"
    volumes:
      - dist:/dist
    networks:
      - web
      - storage
  app:
    container_name: app
    image: mythica-app:latest
    environment:
      MINIO_ENDPOINT: minio:9000
      LOCAL_STORAGE_PATH: /tmp/local_storage
    ports:
      - "50555:5555"
    networks:
      - web
      - storage
volumes:
  dist: # volume reference to share node build contents
networks:
  storage:
    driver: bridge
    name: storage
  web:
    driver: bridge
    name: web
