name: web

#
# This docker compose creates a backend testing environment for 
# storage tier services. You can run this compose set with -d (--detach)
#
services:
  jungle3:
    container_name: jungle3
    image: mythica-jungle3-build:latest
    volumes:
      - dist:/dist
    environment:
      VITE_API_BASE_URL: http://localhost:15555/v1
      VITE_IMAGES_BASE_URL: http://localhost:8080/images
      VITE_AUTH0_DOMAIN: dev-dtvqj0iuc5rnb6x2.us.auth0.com
      VITE_AUTH0_CLIENT_ID: 4CZhQWoNm1WH8l8042LeF38qHrUTR2ax
      VITE_AUTH0_AUDIENCE: http://localhost:15555/v1
      VITE_AUTH0_REDIRECT_URL: http://localhost:8080
  #  editor:
  #    container_name: editor
  #    image: mythica-editor-build:latest
  #    volumes:
  #      - dist:/dist
  nginx:
    container_name: nginx
    image: mythica-web-front:latest
    depends_on:
      - jungle3
      #      - editor
      - app
    ports:
      - "8080:80"
    volumes:
      - dist:/dist
    networks:
      - web
      - storage
  app:
    container_name: app
    image: mythica-app:latest
    environment:
      MINIO_ENDPOINT: minio:9000
      LOCAL_STORAGE_PATH: /tmp/local_storage
    ports:
      - "15555:5555"
    networks:
      - web
      - storage
volumes:
  dist: # volume reference to share node build contents
networks:
  storage:
    driver: bridge
    name: storage
    external: true
  web:
    driver: bridge
    name: web
