#
# This docker compose creates a backend testing environment for 
# storage tier services. You can run this compose set with -d (--detach)
#
services:
  jungle3:
    container_name: jungle3
    image: mythica-jungle3-build:latest
    volumes:
      - dist:/dist
    environment:
      VITE_API_BASE_URL: http://localhost:15555/v1
      VITE_IMAGES_BASE_URL: http://localhost:8080/images
      VITE_AUTH0_DOMAIN: dev-dtvqj0iuc5rnb6x2.us.auth0.com
      VITE_AUTH0_CLIENT_ID: 4CZhQWoNm1WH8l8042LeF38qHrUTR2ax
      VITE_AUTH0_AUDIENCE: http://localhost:15555/v1
      VITE_AUTH0_REDIRECT_URL: http://localhost:8080
#  editor:
#    container_name: editor
#    image: mythica-editor-build:latest
#    volumes:
#      - dist:/dist
  nginx:
    container_name: nginx
    image: mythica-web-front:latest
    depends_on:
      - jungle3
#      - editor
      - app
    ports:
      - "8080:80"
    volumes:
      - dist:/dist
    dns:
      - 34.118.224.10  # Tailscale DNS server for svc.cluster.local
    dns_search:
      - svc.cluster.local  # Ensure svc.cluster.local is a search domain
    dns_opt:
      - ndots:2  # Set ndots to 1
    networks:
      - web
      - storage
  app:
    container_name: app
    image: mythica-app:latest
    environment:
      MINIO_ENDPOINT: minio:9000
      LOCAL_STORAGE_PATH: /tmp/local_storage
    ports:
      - "15555:5555"
    dns:
      - 34.118.224.10  # Tailscale DNS server for svc.cluster.local
    dns_search:
      - svc.cluster.local  # Ensure svc.cluster.local is a search domain
    dns_opt:
      - ndots:2  # Set ndots to 1
    networks:
      - web
      - storage
  otel-collector:
    image: otel/opentelemetry-collector:0.107.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:55679:55679"
    command: >
      /bin/sh -c "otelcontribcol --config=/etc/otel-collector-config.yaml \
      2>&1 | tee collector-output.txt"
volumes:
  dist: # volume reference to share node build contents
networks:
  storage:
    driver: bridge
    name: storage
    external: true
  web:
    driver: bridge
    name: web
