---
# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Nginx metrics receiver
  nginx:
    endpoint: http://nginx:80/nginx_status
    collection_interval: 10s

  # Log receiver for Nginx logs
  filelog:
    include: [ /var/log/nginx/access.log, /var/log/nginx/error.log ]
    start_at: beginning
    operators:
      # Parser for access logs
      - type: regex_parser
        id: access-regex
        regex: '^(?P<remote_addr>[^ ]*) - (?P<remote_user>[^ ]*) \[(?P<time_local>[^\]]*)\] "(?P<request>[^"]*)" (?P<status>[^ ]*) (?P<body_bytes_sent>[^ ]*) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"$'
        timestamp:
          parse_from: attributes.time_local
          layout_type: strptime
          layout: '%d/%b/%Y:%H:%M:%S %z'
        source: access.log

      # Parser for error logs
      - type: regex_parser
        id: error-regex
        regex: '(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): \*(?P<message>.*)'
        timestamp:
          parse_from: attributes.time
          layout_time: strptime
          layout: '%Y/%m/%d %H:%M:%S'
        source: error.log

processors:
  batch:
    timeout: 200ms
    send_batch_size: 512
    send_batch_max_size: 1024


exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: nginx

  debug:
    verbosity: detailed

  otlp:
    endpoint: ingest.us.signoz.cloud:443
    tls:
      insecure: false
    timeout: 10s
    headers:
      "signoz-access-token": ${SIGNOZ_ACCESS_TOKEN}

  # Add optional exporters for logs (example with console output)
  file:
    path: /var/log/export/otel-log.json

service:
  pipelines:
    metrics:
      receivers: [ otlp, nginx ]
      processors: [ memory_limiter, batch ]
      exporters: [ prometheus, debug, otlp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [ filelog, otlp ]
      processors: [ batch ]
      exporters: [ debug, file, otlp ]

  telemetry:
    logs:
      level: "debug"