name: storage

#
# This docker compose creates a backend testing environment for 
# storage tier services. You can run this compose set with -d (--detach)
#
services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: upload_pipeline
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: pg_isready -U test
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - storage
  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - objstore:/objstore
    command: server /objstore --console-address ":9001"
    healthcheck:
      test: mc ping local --count 2
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - storage
  # this is a one shot container to configure the minio access key within
  # the minio service
  minio-config:
    image: minio-config
    depends_on:
      - minio
    build:
      context: ./minio-config
      dockerfile: Dockerfile
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: foo-access
      MINIO_SECRET_KEY: bar-secret
    networks:
      - storage
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - storage
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  nats:
    container_name: nats
    image: nats:alpine
    command: "--jetstream --http_port 8222"
    ports:
      - "4222:4222"  # clients
      - "8222:8222"  # http monitoring
    volumes:
      - nats:/data
    networks:
      - storage
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
  tailscale:
    network_mode: host  # Only this works for docker-compose with specified networks
    container_name: tailscale
    hostname: test-tailscale
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY} # It should be in testing/.env file in this folder
      - TS_EXTRA_ARGS=--reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_ROUTES=34.118.224.0/20,10.0.0.0/8
      - TS_DNS=34.118.224.10
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PGDATA_PATH}
  objstore:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${OBJSTORE_PATH}
  nats:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${NATS_PATH}

networks:
  storage:
    name: storage
    driver: bridge
