# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: automation
  namespace: automation-staging
subjects:
- kind: ServiceAccount
  name: "automation"
roleRef:
  kind: Role
  name: automation
  apiGroup: rbac.authorization.k8s.io
