apiVersion: apps/v1
kind: Deployment
metadata:
  name: houdini
  namespace: automation
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "houdini"
  template:
    metadata:
      labels:
        app: houdini
        tier: automation
        version: "1.0"
        release: production
    spec:
      serviceAccountName: automation
      containers:
        - name: houdini
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-auto-houdini:f9d65a55
          imagePullPolicy: Always
          command: [ "/bin/bash", "houdini.sh" ]
          stdin: true
          tty: true
          env:
            - name: NAMESPACE
              value: api
            - name: TELEMETRY_ENDPOINT
              value: http://otel-collector.default:4317
            - name: TELEMETRY_INSECURE
              value: "true"
            - name: NATS_ENDPOINT
              value: nats://nats.nats:4222
            - name: MYTHICA_ENVIRONMENT
              value: production
<<<<<<< Updated upstream
            - name: MYTHICA_LOCATION  # basically cluster but can be "on-prem"
              value: "gke-main-us-central1"
            - name: K8S_CLUSTER_NAME
              value: "gke-main-us-central1"
            - name: APP_VERSION
              value: "latest"
=======
            - name: MYTHICA_LOCATION
              value: "gke-us-central1"
            - name: SFX_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: SFX_CLIENT_ID
                  name: houdini-secrets
            - name: SFX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: SFX_CLIENT_SECRET
                  name: houdini-secrets
>>>>>>> Stashed changes
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 6Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 6Gi
      restartPolicy: Always
