apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: argo
type: Opaque
data:
  client-id: YXJnby13b3JrZmxvd3Mtc3Nv
  client-secret: Mzc0ZTUzNzYtMjhmNy00YzQ3LThiZmUtYzkwMTNkMmRjMmZm