// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Metadata to store relationships and descriptions of assets
// Table name: assets
export interface Asset {
    asset_seq: number;
    created: string;
    updated: string;
    deleted: string;
    org_seq: number;
    owner_seq: number;
}
// Metadata to store relationships and descriptions of assets
// Table name: asset_versions
export interface AssetVersion {
    asset_seq: number;
    published: boolean;
    major: number;
    minor: number;
    patch: number;
    commit_ref: string;
    created: string;
    name: string;
    description: string;
    author_seq: number;
    package_seq: number;
    contents: object;
}
