// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Metadata to store relationships and descriptions of assets
// Table name: assets
export interface Asset {
    id: string;
    created: string;
    updated: string;
    deleted: string;
    org_id: string;
    owner: string;
}
// Metadata to store relationships and descriptions of assets
// Table name: asset_versions
export interface AssetVersion {
    asset_id: string;
    published: boolean;
    major: number;
    minor: number;
    patch: number;
    commit_ref: string;
    created: string;
    name: string;
    description: string;
    author: string;
    package_id: string;
    contents: object;
}
// Provides a grouping for asset graphs
// Table name: topologies
export interface Topology {
    id: number;
    owner: string;
    org_id: string;
    created: string;
    updated: string;
    name: string;
    description: string;
    edge_data_schema: object;
}
// Records relationships between assets
// Table name: asset_refs
export interface AssetRef {
    topology_id: number;
    src: string;
    dst: string;
    edge_data: object;
}
