// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Storage for events that are used to trigger downstream effects
// Table name: events
export interface Event {
    event_seq: number;
    event_type: string;
    queued: string;
    acked: string;
    completed: string;
    job_data: object;
    owner_seq: number;
    created_in: string;
    affinity: string;
}
