// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Types for storing and referencing rich media (images, etc)
// Table name: files
export interface FileContent {
    id: string;
    name: string;
    created: string;
    updated: string;
    deleted: string;
    size: number;
    content_type: string;
    uri: string;
    owner: string;
    cache_ttl: number;
    downloads: number;
    lifetime: number;
    content_hash: string;
    locators: object;
}
