// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Types to represent profiles online
// Table name: profiles
export interface Profile {
    profile_seq: number;
    name: string;
    full_name: string;
    signature: string;
    created: string;
    updated: string;
    active: boolean;
    profile_base_href: string;
    description: string;
    email: string;
    email_validate_state: number;
    location: string;
    login_count: number;
}
// Types to represent profiles online
// Table name: org_refs
export interface OrgRef {
    org_seq: number;
    profile_seq: string;
    role: string;
    created: string;
    author_seq: number;
}
// Types to represent profiles online
// Table name: orgs
export interface Org {
    org_seq: number;
    created: string;
    updated: string;
    name: string;
    description: string;
}
// Types to represent profiles online
// Table name: profile_sessions
export interface ProfileSession {
    profile_session_seq: number;
    created: string;
    refreshed: string;
    profile_seq: number;
    authenticated: boolean;
    auth_token: string;
    refresh_token: string;
    location: string;
}
// Types to represent profiles online
// Table name: profile_followers
export interface ProfileFollower {
    profile_seq: number;
    follower_seq: number;
    created: string;
    deleted: string;
}
// Types to represent profiles online
// Table name: profile_keys
export interface ProfileKey {
    key: string;
    owner_seq: number;
    expires: string;
    payload: object;
}
