apiVersion: v1
kind: Service
metadata:
  name: nats-internal
  namespace: nats
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/neg: '{"exposed_ports": {"4222":{}}}'
    tailscale.com/expose: "true"
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  type: LoadBalancer
  ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    protocol: TCP
    targetPort: nats
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
