global:
  storageClass: gce-resizable
  cloud: gcp/autogke
  clusterName: gke-main-us-central1
  deploymentEnvironment: api-staging
otelCollectorEndpoint: ingest.us.signoz.cloud:443
otelInsecure: false
signozApiKey: ...
presets:
  kubeletMetrics:
    authType: none
    endpoint: ${K8S_NODE_NAME}:10255
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  resourceDetection:
    detectors:
      - gcp
      - system