rails-application:
  name: docker-registry-browser
  version: latest

  image:
    repository: klausmeyer/docker-registry-browser

  environment:
    # sealedSecrets: false
    plain: 
      DOCKER_REGISTRY_URL: "http://registry:5000"
      PUBLIC_REGISTRY_URL: "https://registry.mythica.gg"
      SECRET_KEY_BASE: "registry"
      NO_SSL_VERIFICATION: "false"
      SCRIPT_NAME: "/browser"
      RAILS_RELATIVE_URL_ROOT: "/browser"
    secret: {}
    #  ANYTHING: "ANYTHING"

  deployments:
    web:
      enabled: true
      livenessProbe:
        httpGet:
          path: /ping
          port: http
      readinessProbe:
        httpGet:
          path: /ping
          port: http
