"""add job inputs

Revision ID: 16677d466e37
Revises: e09bddf061f9
Create Date: 2024-09-09 21:03:46.617107+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16677d466e37'
down_revision: Union[str, None] = 'e09bddf061f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_defs', sa.Column('input_files', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_defs', 'input_files')
    # ### end Alembic commands ###
