"""email validate

Revision ID: 1a58818a4e8e
Revises: ad52c1cad678
Create Date: 2024-06-19 21:23:58.688575+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a58818a4e8e'
down_revision: Union[str, None] = 'ad52c1cad678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email_validate_state', sa.Integer(), nullable=True))
    op.drop_column('profiles', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'email_validate_state')
    # ### end Alembic commands ###
