"""Fix link table index

Revision ID: 23ee0bbb9213
Revises: 78c9325f2e68
Create Date: 2025-01-28 21:40:08.675819+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23ee0bbb9213'
down_revision: Union[str, None] = '78c9325f2e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_version_entry_points', 'src_file_seq',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('asset_version_entry_points', 'entry_point',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('asset_version_entry_points_src_file_seq_fkey', 'asset_version_entry_points', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('asset_version_entry_points_src_file_seq_fkey', 'asset_version_entry_points', 'files', ['src_file_seq'], ['file_seq'])
    op.alter_column('asset_version_entry_points', 'entry_point',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('asset_version_entry_points', 'src_file_seq',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
