"""add entry point link table

Revision ID: 29c42c5870bc
Revises: 1f4d590c2e28
Create Date: 2025-01-16 18:42:50.399624+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29c42c5870bc'
down_revision: Union[str, None] = '1f4d590c2e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_version_entry_points',
    sa.Column('asset_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('src_file_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entry_point', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_def_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['job_def_seq'], ['job_defs.job_def_seq'], ),
    sa.ForeignKeyConstraint(['src_file_seq'], ['files.file_seq'], ),
    sa.PrimaryKeyConstraint('asset_seq', 'major', 'minor', 'patch')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_version_entry_points')
    # ### end Alembic commands ###
