"""add OID profile locator table

Revision ID: 346f0ebeb5ae
Revises: e09bddf061f9
Create Date: 2024-09-09 19:47:19.556542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '346f0ebeb5ae'
down_revision: Union[str, None] = 'e09bddf061f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_locators_oid',
    sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['owner_seq'], ['profiles.profile_seq'], ),
    sa.PrimaryKeyConstraint('sub')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_locators_oid')
    # ### end Alembic commands ###
