"""Add visibility column to files

Revision ID: 376103d16d78
Revises: c5ee0dfdaaf4
Create Date: 2024-11-29 12:08:03.326931+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '376103d16d78'
down_revision: Union[str, None] = 'c5ee0dfdaaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'visibility')
    # ### end Alembic commands ###
