"""migrate role names

Revision ID: 59a02ca9a963
Revises: 3c8b04c8e71c
Create Date: 2024-11-05 12:21:26.998525+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59a02ca9a963'
down_revision: Union[str, None] = '3c8b04c8e71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # this role is now handled in session_start
    op.execute("delete from org_refs where role = 'mythica-tags' ")

    # migrate some old names to least privilege org-members
    op.execute("update org_refs set role = 'org-member' where role = 'member' ")
    op.execute("update org_refs set role = 'org-member' where role = 'user' ")
    op.execute("update org_refs set role = 'org-member' where role = 'dev' ")
    op.execute("update org_refs set role = 'org-admin' where role = 'admin' ")
    op.execute("update org_refs set role = 'org-mod' where role = 'mod' ")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
