"""bigint and sequence conversion

Revision ID: 748f001d63eb
Revises: 52d8ee71f1ef
Create Date: 2024-09-05 18:15:07.818655+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.ddl import CreateSequence, DropSequence

from db.schema.jobs import job_results_job_result_seq_seq

# revision identifiers, used by Alembic.
revision: str = '748f001d63eb'
down_revision: Union[str, None] = '52d8ee71f1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_versions', 'asset_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('asset_versions', 'author_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    nullable=True)
    op.alter_column('asset_versions', 'package_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('assets', 'asset_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('assets', 'org_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('assets', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('events', 'event_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('events', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('files', 'file_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('files', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('job_defs', 'job_def_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('job_results', 'job_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('job_results', 'job_result_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('jobs', 'job_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('jobs', 'job_def_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    nullable=True)
    op.alter_column('jobs', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('org_refs', 'org_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('org_refs', 'profile_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('org_refs', 'author_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('orgs', 'org_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('orgs_org_seq_seq'::regclass)"))
    op.alter_column('profile_followers', 'profile_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('profile_followers', 'follower_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.alter_column('profile_keys', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('profile_sessions', 'profile_session_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('profile_sessions', 'profile_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    nullable=True)
    op.alter_column('profiles', 'profile_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('profiles_profile_seq_seq'::regclass)"))
    op.alter_column('topologies', 'topology_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('topologies', 'owner_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('topologies', 'org_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=True)
    op.alter_column('topology_refs', 'topology_seq',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    existing_nullable=False)
    op.execute(CreateSequence(job_results_job_result_seq_seq))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topology_refs', 'topology_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('topologies', 'org_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('topologies', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('topologies', 'topology_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('profiles', 'profile_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('profiles_profile_seq_seq'::regclass)"))
    op.alter_column('profile_sessions', 'profile_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('profile_sessions', 'profile_session_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('profile_keys', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('profile_followers', 'follower_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('profile_followers', 'profile_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('orgs', 'org_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('orgs_org_seq_seq'::regclass)"))
    op.alter_column('org_refs', 'author_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('org_refs', 'profile_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('org_refs', 'org_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('jobs', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('jobs', 'job_def_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('jobs', 'job_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('job_results', 'job_result_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('job_results', 'job_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('job_defs', 'job_def_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('files', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('files', 'file_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('events', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('events', 'event_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('assets', 'owner_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('assets', 'org_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('assets', 'asset_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    autoincrement=True)
    op.alter_column('asset_versions', 'package_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.alter_column('asset_versions', 'author_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('asset_versions', 'asset_seq',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.execute(DropSequence(job_results_job_result_seq_seq))
    # ### end Alembic commands ###
