"""asset field refactor

Revision ID: 74d07ff4f506
Revises: 1a58818a4e8e
Create Date: 2024-06-24 18:56:43.741911+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74d07ff4f506'
down_revision: Union[str, None] = '1a58818a4e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('asset_versions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('assets', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('asset_versions', 'description')
    op.drop_column('asset_versions', 'published')
    # ### end Alembic commands ###
