"""adding downloads column

Revision ID: 7c5552bdb058
Revises: 74d07ff4f506
Create Date: 2024-07-14 07:06:47.174978+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5552bdb058'
down_revision: Union[str, None] = '74d07ff4f506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('downloads', sa.Integer(), nullable=True))
    op.drop_column('profile_sessions', 'updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_sessions', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('files', 'downloads')
    # ### end Alembic commands ###
