"""initial

Revision ID: 869cd6d827a9
Revises: 
Create Date: 2024-06-06 02:50:04.509897+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '869cd6d827a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('cache_ttl', sa.Integer(), nullable=True),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locators', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_followers',
    sa.Column('profile_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('follow_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id', 'follow_id')
    )
    op.create_table('profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('profile_base_href', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edge_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_refs',
    sa.Column('src', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('dst', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('edge_data', sa.JSON(), nullable=True),
    sa.Column('topology_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topologies.id'], ),
    sa.PrimaryKeyConstraint('src', 'dst')
    )
    op.create_table('asset_versions',
    sa.Column('asset_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('commit_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('package_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('contents', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'major', 'minor', 'patch')
    )
    op.create_table('assets',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queued', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('job_data', sa.JSON(), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_in', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affinity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('refreshed', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('auth_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_sessions')
    op.drop_table('org_refs')
    op.drop_table('events')
    op.drop_table('assets')
    op.drop_table('asset_versions')
    op.drop_table('asset_refs')
    op.drop_table('topologies')
    op.drop_table('profiles')
    op.drop_table('profile_followers')
    op.drop_table('orgs')
    op.drop_table('files')
    # ### end Alembic commands ###
