"""Remove deprecated job fields

Revision ID: 880af339c27c
Revises: c87f625c948c
Create Date: 2024-10-15 16:45:09.849414+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880af339c27c'
down_revision: Union[str, None] = 'c87f625c948c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_defs', 'config')
    op.drop_column('job_defs', 'input_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_defs', sa.Column('input_files', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_defs', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
