"""update

Revision ID: 9453f200b29d
Revises: e7fab4351a4b
Create Date: 2024-06-10 16:31:30.388738+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9453f200b29d'
down_revision: Union[str, None] = 'e7fab4351a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('org_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_column('assets', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'org_id')
    # ### end Alembic commands ###
