"""topology update

Revision ID: c62c45f4fb2f
Revises: 869cd6d827a9
Create Date: 2024-06-07 19:10:29.731694+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c62c45f4fb2f'
down_revision: Union[str, None] = '869cd6d827a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_refs', 'topology_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('asset_refs_topology_id_fkey', 'asset_refs', type_='foreignkey')
    op.add_column('topologies', sa.Column('owner', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('topologies', sa.Column('org_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('topologies', sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('topologies', sa.Column('edge_data_schema', sa.JSON(), nullable=True))
    op.drop_column('topologies', 'edge_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topologies', sa.Column('edge_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('topologies', 'edge_data_schema')
    op.drop_column('topologies', 'updated')
    op.drop_column('topologies', 'org_id')
    op.drop_column('topologies', 'owner')
    op.create_foreign_key('asset_refs_topology_id_fkey', 'asset_refs', 'topologies', ['topology_id'], ['id'])
    op.alter_column('asset_refs', 'topology_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
