"""add reader direction

Revision ID: c87f625c948c
Revises: 48f4e15118ea
Create Date: 2024-09-24 21:03:30.892065+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c87f625c948c'
down_revision: Union[str, None] = '48f4e15118ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('direction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'direction')
    # ### end Alembic commands ###
