"""topology update

Revision ID: e7fab4351a4b
Revises: c62c45f4fb2f
Create Date: 2024-06-07 21:50:00.618194+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7fab4351a4b'
down_revision: Union[str, None] = 'c62c45f4fb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_refs', sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('org_refs', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('org_refs_org_id_fkey', 'org_refs', type_='foreignkey')
    op.drop_constraint('org_refs_profile_id_fkey', 'org_refs', type_='foreignkey')
    op.create_foreign_key(None, 'org_refs', 'profiles', ['created_by'], ['id'])
    op.drop_column('org_refs', 'updated')
    op.drop_column('org_refs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_refs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('org_refs', sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'org_refs', type_='foreignkey')
    op.create_foreign_key('org_refs_profile_id_fkey', 'org_refs', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key('org_refs_org_id_fkey', 'org_refs', 'orgs', ['org_id'], ['id'])
    op.alter_column('org_refs', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('org_refs', 'created_by')
    # ### end Alembic commands ###
