---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ingress
  name: lets-encrypt-secret-access
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ingress
  name: lets-encrypt
subjects:
  - kind: ServiceAccount
    name: lets-encrypt
    namespace: api
  - kind: ServiceAccount
    name: lets-encrypt
    namespace: api-staging
roleRef:
  kind: Role
  name: lets-encrypt-secret-access
  apiGroup: rbac.authorization.k8s.io