---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ingress
  name: lets-encrypt
subjects:
  - kind: ServiceAccount
    name: lets-encrypt
    namespace: api
roleRef:
  kind: Role
  name: lets-encrypt-secret-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ingress
  name: lets-encrypt
subjects:
  - kind: ServiceAccount
    name: lets-encrypt
    namespace: api-staging
roleRef:
  kind: Role
  name: lets-encrypt-secret-access
  apiGroup: rbac.authorization.k8s.io
