"""Add File src_file_seq

Revision ID: 1c2d454068e7
Revises: 981d79320d84
Create Date: 2025-02-21 12:12:17.056225+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c2d454068e7'
down_revision: Union[str, None] = '981d79320d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('src_file_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.create_foreign_key(None, 'files', 'files', ['src_file_seq'], ['file_seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'src_file_seq')
    # ### end Alembic commands ###
