"""empty message

Revision ID: 5bc85a3be0fb
Revises: 1c2d454068e7
Create Date: 2025-03-14 10:27:41.129503+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5bc85a3be0fb'
down_revision: Union[str, None] = '1c2d454068e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_defs', sa.Column('interactive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_defs', 'interactive')
    # ### end Alembic commands ###
