"""add blurb to asset version

Revision ID: 78c9325f2e68
Revises: 29c42c5870bc
Create Date: 2025-01-28 18:02:12.854228+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78c9325f2e68'
down_revision: Union[str, None] = '29c42c5870bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('blurb', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_versions', 'blurb')
    # ### end Alembic commands ###
