"""AssetVersion add deleted field

Revision ID: de5f9c85e5e5
Revises: 59a02ca9a963
Create Date: 2024-11-19 15:37:07.181964+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de5f9c85e5e5'
down_revision: Union[str, None] = '59a02ca9a963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_versions', sa.Column('deleted', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_versions', 'deleted')
    # ### end Alembic commands ###
