"""add_oid_profile_locator_table

Revision ID: ff334bf9e017
Revises: dad56840116b
Create Date: 2024-09-11 18:07:43.837658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff334bf9e017'
down_revision: Union[str, None] = 'dad56840116b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_locators_oid',
    sa.Column('sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['owner_seq'], ['profiles.profile_seq'], ),
    sa.PrimaryKeyConstraint('sub')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_locators_oid')
    # ### end Alembic commands ###
