// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Metadata to store relationships and descriptions of assets
// Table name: assets
export interface Asset {
    id: string;
    created: string;
    updated: string;
    deleted: string;
    collection_id: string;
    owner: string;
}
// Metadata to store relationships and descriptions of assets
// Table name: asset_versions
export interface AssetVersion {
    asset_id: string;
    major: number;
    minor: number;
    patch: number;
    created: string;
    content_hash: string;
    friendly_name: string;
    tags: object;
    author: string;
}
// Provides a natural grouping for asset graphs
// Table name: topologies
export interface Topology {
    id: number;
    created: string;
    name: string;
    description: string;
    edge_data: object;
}
// Records relationships between assets
// Table name: asset_refs
export interface AssetRef {
    src: string;
    dst: string;
    edge_data: object;
    topology_id: number;
}
