// AUTOGENERATED: this file has been auto-generated by fileassetkit,
// instead of modifying this file, modify the source contents in
// fileassetkit.schema
//


// models
// Types to represent profiles online
// Table name: profiles
export interface Profile {
    id: string;
    name: string;
    signature: string;
    created: string;
    updated: string;
    active: boolean;
    tags: object;
    profile_base_href: string;
    description: string;
    email_verified: boolean;
    location: string;
    login_count: number;
}
// Types to represent profiles online
// Table name: org_refs
export interface OrgRef {
    id: number;
    created: string;
    updated: string;
    profile_id: string;
    org_id: string;
    role: string;
}
// Types to represent profiles online
// Table name: orgs
export interface Org {
    id: string;
    created: string;
    updated: string;
    name: string;
    description: string;
    tags: object;
}
// Types to represent profiles online
// Table name: profile_sessions
export interface ProfileSession {
    id: string;
    created: string;
    updated: string;
    refreshed: string;
    profile_id: string;
    authenticated: boolean;
    auth_token: string;
    refresh_token: string;
}
// Types to represent profiles online
// Table name: profile_followers
export interface ProfileFollower {
    ref_profile_id: string;
    ref_follow_id: string;
    created: string;
    deleted: string;
}
