apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: front-end-api
  name: front-end-api-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
