apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-service-account
  namespace: api-staging
  annotations:
    iam.gke.io/gcp-service-account: github-actions-service-account@controlnet-407314.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api-staging
  name: secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-secret-reader
  namespace: api-staging
subjects:
  - kind: ServiceAccount
    name: github-actions-service-account
    namespace: api-staging
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
