apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: {{ .Release.Namespace }}
  annotations:
    config-update: "2024-10-04"
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:

    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: ingest.us.signoz.cloud:443
        tls:
          insecure: false
        timeout: 10s
        headers:
          "signoz-access-token": ...

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlp]
