apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: otel-agent
  template:
    metadata:
      labels:
        app: otel-agent
    spec:
      containers:
        - name: otel-agent
          image: otel/opentelemetry-collector-contrib
          ports:
          - containerPort: 4317
          env:
            - name: SIGNOZ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SIGNOZ_API_KEY
