apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-agent
  template:
    metadata:
      labels:
        app: otel-agent
    spec:
      containers:
        - name: otel-agent
          image: otel/opentelemetry-collector-contrib
          ports:
            - containerPort: 4317
          env:
            - name: SIGNOZ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: otel-secrets
                  key: SIGNOZ_API_KEY
