apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
  annotations:
    config-update: "2024-11-12"
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:55681"

      # Data sources: metrics
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 5s
              static_configs:
                - targets: [localhost:8888]

    exporters:
      logging:
        verbosity: detailed
      otlp:
        endpoint: ingest.us.signoz.cloud:443
        tls:
          insecure: false
        timeout: 10s
        headers:
          "signoz-access-token": ${SIGNOZ_API_KEY}

    processors:
        batch:
          timeout: 5s
          send_batch_size: 1024
          send_batch_max_size: 8192

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
