apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP  # gRPC uses TCP as its transport protocol
    - name: http
      port: 55681
      targetPort: 55681
      protocol: TCP  # Optional for HTTP communication
  selector:
    app: otel-collector