# AUTOGENERATED from fileassetkit.schema
#
#
from sqlalchemy import JSON, TIMESTAMP, Column, func, text
from sqlalchemy.sql.functions import now as sql_now
from sqlmodel import Field, SQLModel, create_engine, Session
from pydantic import ConfigDict
from typing import Any, Dict
from datetime import datetime
from uuid import UUID, uuid4



class Asset(SQLModel, table=True):
    """
    Metadata to store relationships and descriptions of assets
    """
    __tablename__ = "assets"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=True)
    created: datetime | None = Field(sa_type=TIMESTAMP(timezone=True), sa_column_kwargs={'server_default': sql_now(), 'nullable': False})
    updated: datetime | None = Field(default=None, sa_type=TIMESTAMP(timezone=True), sa_column_kwargs={'server_onupdate': sql_now(), 'nullable': True})
    deleted: datetime | None = None
    collection_id: UUID | None = uuid4()
    owner: UUID | None = Field(foreign_key='profiles.id')


class AssetVersion(SQLModel, table=True):
    """
    Metadata to store relationships and descriptions of assets
    """
    __tablename__ = "asset_versions"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types
    asset_id: UUID = Field(primary_key=True, nullable=False)
    major: int = Field(primary_key=True, nullable=False)
    minor: int = Field(primary_key=True, nullable=False)
    patch: int = Field(primary_key=True, nullable=False)
    created: datetime | None = Field(sa_type=TIMESTAMP(timezone=True), sa_column_kwargs={'server_default': sql_now(), 'nullable': False})
    content_hash: str = None
    friendly_name: str | None = None
    tags: Dict[str, Any] | None = Field(default_factory=dict, sa_column=Column(JSON))
    author: UUID = Field(foreign_key='profiles.id')


class Topology(SQLModel, table=True):
    """
    Provides a natural grouping for asset graphs
    """
    __tablename__ = "topologies"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types
    id: int | None = Field(primary_key=True, nullable=True)
    created: datetime | None = Field(sa_type=TIMESTAMP(timezone=True), sa_column_kwargs={'server_default': sql_now(), 'nullable': False})
    name: str | None = None
    description: str | None = None
    edge_data: Dict[str, Any] | None = Field(default_factory=dict, sa_column=Column(JSON))


class AssetRef(SQLModel, table=True):
    """
    Records relationships between assets
    """
    __tablename__ = "asset_refs"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types
    src: UUID | None = Field(primary_key=True, nullable=True)
    dst: UUID | None = Field(primary_key=True, nullable=True)
    edge_data: Dict[str, Any] | None = Field(default_factory=dict, sa_column=Column(JSON))
    topology_id: int | None = Field(foreign_key='topologies.id')
