# AUTOGENERATED from fileassetkit.schema
#
#
# pylint: disable=unused-import
from sqlalchemy import JSON, TIMESTAMP, Column, func, text
from sqlalchemy.types import Integer, BigInteger
from sqlalchemy.sql.functions import now as sql_now
from sqlalchemy.sql.schema import Sequence, ForeignKey
from sqlalchemy.sql.ddl import CreateSequence, DropSequence
from sqlalchemy.ext.declarative import declared_attr
from sqlmodel import Field, SQLModel
from pydantic import ConfigDict
from typing import Any, Dict
from datetime import datetime
from uuid import UUID, uuid4


# sequences for table events

class Event(SQLModel, table=True):
    """
    Storage for events that are used to trigger downstream effects
    """
    __tablename__ = "events"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types

    @declared_attr
    def __table_args__(cls):
        # ensure auto increment behavior on non-PK int columns
        return ({'sqlite_autoincrement': True}, )

    event_seq: int = Field(sa_column=Column('event_seq',BigInteger().with_variant(Integer, 'sqlite'),primary_key=True,nullable=False))
    event_type: str = Field(default=None)
    queued: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),sa_column_kwargs={'server_default': sql_now(), 'nullable': False},default=None)
    acked: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),default=None)
    completed: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),default=None)
    job_data: Dict[str, Any] = Field(default_factory=dict,sa_column=Column(JSON))
    owner_seq: int | None = Field(sa_column=Column('owner_seq',BigInteger().with_variant(Integer, 'sqlite'),ForeignKey('profiles.profile_seq'),default=None))
    created_in: str | None = Field(default=None)
    affinity: str | None = Field(default=None)
