# AUTOGENERATED from fileassetkit.schema
#
#
# pylint: disable=unused-import
from sqlalchemy import JSON, TIMESTAMP, Column, func, text
from sqlalchemy.types import Integer, BigInteger
from sqlalchemy.sql.functions import now as sql_now
from sqlalchemy.sql.schema import Sequence, ForeignKey
from sqlalchemy.sql.ddl import CreateSequence, DropSequence
from sqlmodel import Field, SQLModel
from pydantic import ConfigDict
from typing import Any, Dict
from datetime import datetime
from uuid import UUID, uuid4


# sequences for table job_defs

class JobDefinition(SQLModel, table=True):
    """
    The schema for job and job result tracking
    """
    __tablename__ = "job_defs"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types

    job_def_seq: int = Field(sa_column=Column('job_def_seq',BigInteger().with_variant(Integer, 'sqlite'),primary_key=True,nullable=False))
    job_type: str | None = Field(default=None)
    name: str | None = Field(default=None)
    description: str | None = Field(default=None)
    config: Dict[str, Any] | None = Field(default_factory=dict,sa_column=Column(JSON))
    params_schema: Dict[str, Any] | None = Field(default_factory=dict,sa_column=Column(JSON))

# sequences for table jobs

class Job(SQLModel, table=True):
    """
    The schema for job and job result tracking
    """
    __tablename__ = "jobs"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types

    job_seq: int = Field(sa_column=Column('job_seq',BigInteger().with_variant(Integer, 'sqlite'),primary_key=True,nullable=False))
    job_def_seq: int = Field(sa_column=Column('job_def_seq',BigInteger().with_variant(Integer, 'sqlite'),ForeignKey('job_defs.job_def_seq'),default=None))
    owner_seq: int | None = Field(sa_column=Column('owner_seq',BigInteger().with_variant(Integer, 'sqlite'),ForeignKey('profiles.profile_seq'),default=None))
    created: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),sa_column_kwargs={'server_default': sql_now(), 'nullable': False},default=None)
    completed: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),default=None)
    deleted: datetime | None = Field(sa_type=TIMESTAMP(timezone=True),default=None)
    params: Dict[str, Any] | None = Field(default_factory=dict,sa_column=Column(JSON))

# sequences for table job_results
job_results_job_result_seq_seq: Sequence = Sequence(name='job_results_job_result_seq_seq', start=1)

class JobResult(SQLModel, table=True):
    """
    The schema for job and job result tracking
    """
    __tablename__ = "job_results"
    model_config = ConfigDict(arbitrary_types_allowed=True)  # JSON types

    job_seq: int = Field(sa_column=Column('job_seq',BigInteger().with_variant(Integer, 'sqlite'),primary_key=True,nullable=False))
    job_result_seq: int = Field(sa_column=Column('job_result_seq',BigInteger().with_variant(Integer, 'sqlite'),job_results_job_result_seq_seq,primary_key=True,nullable=False))
    created_in: str | None = Field(default=None)
    result_data: Dict[str, Any] = Field(default_factory=dict,sa_column=Column(JSON))
