{{- if eq .Values.gke.enabled true }}
{{- $componentContext := .Values.api.gcsProxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentContext.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $componentContext.replicas | default 1 }}
  strategy:
    {{- include "api.rolloutStrategy" $componentContext | nindent 4 }}
  selector:
    matchLabels:
      app: {{ $componentContext.name }}
  template:
    metadata:
      labels:
        {{- include "api.commonLabels" . | nindent 8 }}
        {{- include "api.componentLabels" $componentContext | nindent 8 }}
    spec:
      {{- include "api.nodeSelector" $componentContext | nindent 6 }}
      terminationGracePeriodSeconds: {{ $componentContext.terminationGracePeriodSeconds }}
      serviceAccountName: api
      containers:
        - name: gcs-proxy
          image: {{ include "api.image" (list . "mythica-gcs-proxy") }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http-proxy
      restartPolicy: Always
{{ end }}