{{- if eq .Values.gke.enabled true -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: web-front
  namespace: {{ .Values.namespace }}
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        host: api.mythica.ai
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: web-front
{{- end -}}