apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lets-encrypt
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
