apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: lets-encrypt
subjects:
  - kind: ServiceAccount
    name: lets-encrypt
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: lets-encrypt-secret-access
  apiGroup: rbac.authorization.k8s.io

