apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: {{ .Values.namespace }}
{{- if eq .Values.gke.enabled true }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.email }}
{{- end }}
