apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        app: api-v1
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/ephemeral-storage-limit: "50Gi"
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Scale-Out"
      securityContext:
        fsGroup: 100
      terminationGracePeriodSeconds: 60
      serviceAccountName: api
      containers:
        - name: gke-gcsfuse-sidecar
          image: gcs-fuse-csi-driver-sidecar-mounter:v1.2.0
          resources:
            requests:
              memory: "2Gi"
              ephemeral-storage: "50Gi"
        - name: api-v1
          image: us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images/mythica-web-front:e70ff1be
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: gcs-fuse-csi-ephemeral-web-content
              mountPath: /data
              readOnly: true
            - name: gcs-fuse-csi-ephermal-upload-content
              mountPath: /uploads
              readOnly: false
      volumes:
        # Nodal ephemeral volume used by the CSI driver
        - name: gcs-fuse-csi-ephemeral-web-content
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: true
            volumeAttributes:
              bucketName: mythica-public-web-content
              mountOptions: "implicit-dirs"
              gcsfuseLoggingSeverity: warning
              fileCacheCapacity: "40Gi"
        - name: gcs-fuse-csi-ephermal-upload-content
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: false
            volumeAttributes:
              bucketName: hda-ingest
              mountOptions: "implicit-dirs"
              gcsfuseLoggingSeverity: warning
              fileCacheCapacity: "10Gi"
      restartPolicy: Always
