name: api/app tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'api/app/**'

defaults:
  run:
    working-directory: api/app

jobs:
  api-app-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    env:
      SQL_URL: "sqlite:///${{ github.workspace }}/mythica.db"
      DATABASE_PATH: "${{ github.workspace }}/mythica.db"
      PYTHONPATH: "${{ github.workspace }}/api/app"
      UPLOAD_FOLDER_AUTO_CLEAN: false
      LOCAL_STORAGE_PATH: /tmp/local_storage
      USE_LOCAL_STORAGE: true
      COVERAGE_SINGLE: 80
      COVERAGE_TOTAL: 80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with=dev --no-root
      - name: Static Code Linting with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Create SQLite database
        run: |
          touch $DATABASE_PATH

      - name: Initialize Database
        run: |
          mkdir alembic_sqlite/versions
          poetry run alembic -n sqlite revision --autogenerate -m "initial"

      - name: Create Schema
        run: |
          poetry run alembic -n sqlite upgrade head
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR

      - name: Run tests
        id: pytester-cov
        uses: ./github_coverage/run_coverage/
        with:
          pytest-root-dir: '.'
          cov-omit-list: 'tests/*'
          cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
          cov-threshold-total: ${{ env.COVERAGE_TOTAL }}

      - name: Comment table-result inside PR
        uses: ./github_coverage/post_git_issue/
        # pass user input as arguments
        with:
          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          # labels: workflow-output-table
          body: ${{ steps.pytester-cov.outputs.output-table }}
          repo: ${{ github.repository }}
          pull_number: ${{ steps.PR.outputs.number }}
