name: api/app tests

on:
  pull_request:
    paths:
      - 'api/app/**'

defaults:
  run:
    working-directory: api/app

jobs:
  api-app-ci:
    runs-on: ubuntu-latest

    env:
      SQL_URL: "sqlite:///${{ github.workspace }}/mythica.db"
      DATABASE_PATH: "${{ github.workspace }}/mythica.db"
      PYTHONPATH: "${{ github.workspace }}/api/app"
      ENABLE_STORAGE: false
      UPLOAD_FOLDER_AUTO_CLEAN: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with=dev --no-root
      - name: Static Code Linting with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Create SQLite database
        run: |
          touch $DATABASE_PATH

      - name: Initialize Database
        run: |
          mkdir alembic_sqlite/versions
          poetry run alembic -n sqlite revision --autogenerate -m "initial"

      - name: Create Schema
        run: |
          poetry run alembic -n sqlite upgrade head

      - name: Run tests
        run: |
          poetry run pytest .
