name: api/app tests

on:
  push:
    paths:
      - 'api/app/**'
  pull_request:
    paths:
      - 'api/app/**'

jobs:
  db-setup:
    runs-on: ubuntu-latest

    env:
      SQL_URL: "sqlite:///${{ github.workspace }}/mythica.db"
      DATABASE_PATH: "${{ github.workspace }}/mythica.db"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/app/requirements.txt
          pip install -r api/app/tests/requirements.txt

      - name: Create SQLite database
        run: |
          touch $DATABASE_PATH

      - name: Initialize Database
        run: |
          cd api/app
          mkdir alembic_sqlite/versions
          alembic -n sqlite revision --autogenerate -m "initial"

      - name: Create Schema
        run: |
          cd api/app
          alembic -n sqlite upgrade head

      - name: Run tests
        run: |
          cd api/app
          pytest .
