name: Deploy Helm Chart

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: api/helm

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    env:
      NODE_ENV: "production"
      PROJECT_ID: "296075347103"
      AR_REPO_LOCATION: 'us-central1'
      SERVICE_ACCOUNT: 'github-actions-service-account@controlnet-407314.iam.gserviceaccount.com'
      GKE_CLUSTER_NAME: 'gke-main-us-central1'
      WORKLOAD_IDENTITY_PROVIDER: 'projects/296075347103/locations/global/workloadIdentityPools/gh-infra-pool/providers/github-mythica-infra'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up Kubernetes credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} \
            --project ${{ env.PROJECT_ID }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install --namespace api-staging -f api/values-staging.yaml api-staging ./api
