name: p4-commit-hook

on:
  # Run when this file itself changes
  push:
    paths:
      - '.github/workflows/bulk-import-github.yaml'
      - 'api/bulk-import/**'

  workflow_dispatch:
    inputs:
      endpoint:
        description: 'Force full sync'
        required: false
        type: boolean
        default: false
env:
  REPO_BASE: /mnt/p4/github-scratch

jobs:
  sync-and-process:
    runs-on: p4-automation
    concurrency: bulk-import-github # only one job at a time accessing the perforce client
    steps:
      - name: Checkout github
        uses: actions/checkout@v4

      - name: System diag
        run: |
          # these should be already installed on the system
          which python3.11
          which poetry

      - name: Bulk Import GitHub Changes
        working-directory: api/bulk-import
        run: |
          # Example: Get latest changelist
          LATEST_CL=$(p4 -u $P4USER -P $P4PASSWD changes -m 1 //depot/... | cut -d' ' -f2)
          echo "Latest changelist: $LATEST_CL"
          
          # bulk import HDA packages
          poetry install --no-root
          poetry env info
          poetry run python3.11 upload_packages.py \
            --package-list package_list.py \
            --endpoint https://api-staging.mythica.gg \
            --repo-base ${REPO_BASE} \
            --mythica-api-key ${{ secrets.BULK_IMPORT_STAGING_MYTHICA_API_KEY }} \
            --github-api-token ${{ secrets.BULK_IMPORT_GITHUB_API_KEY }} \
            --license MPLv2.txt \
            --tag "Open Source" \
            --markdown results.md
          cat results.md
          cat results.md >> $GITHUB_STEP_SUMMARY
