name: helm-deploy-api-staging-a

on:
  # trigger helm deploy when new images are available
  workflow_run:
    workflows: [ "push-tagged-images" ]
    types:
      - completed

  # trigger helm deploy when the helm or gha config changes
  push:
    branches:
      - '**'
    paths:
      - 'workloads/helm/**'
      - '.github/workflows/helm-deploy-api-staging-a.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: .

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      NODE_ENV: "staging"
      KUBECONFIG: /tmp/kubeconfig
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Generate values file for image tags
        run: |
          workloads/helm/api/helm-gen-values-images.sh

      - name: Tailscale Auth
        id: tailscale-auth
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_MYTHICA_A }}" | base64 -d > $KUBECONFIG

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        working-directory: workloads/helm
        run: |
          helm upgrade --namespace api-staging -f api/values-staging-a.yaml -f api/values-images.yaml api-staging api
          echo "## Upgraded image versions" >> $GITHUB_STEP_SUMMARY
          cat ./api/values-images.yaml >> $GITHUB_STEP_SUMMARY
          helm upgrade otel-release-k8s-infra ./otel -f ./otel/values.yaml -n default

      - name: Rollout deployments
        run: |
          kubectl rollout restart deployment/otel-agent -n default
          kubectl rollout restart deployment/otel-collector -n default
          kubectl rollout restart deployment/app -n api-staging
          kubectl rollout restart deployment/packager -n api-staging
          kubectl rollout restart deployment/lets-encrypt -n api-staging
          kubectl rollout restart deployment/gcs-proxy -n api-staging
          kubectl rollout restart deployment/web-front -n api-staging
          kubectl rollout restart deployment/canary -n api-staging
