name: libs-python-ci

on:
  push:
    branches:
      - '**'
    paths:
      - 'libs/python/**'
      - '.github/workflows/libs-python-ci.yaml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'libs/**'
      - '.github/workflows/libs-python-ci.yaml'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    outputs:
      libraries: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filters: |
            libs/python/cryptid:
              - 'libs/python/cryptid/**'
            libs/python/ripple:
              - 'libs/python/ripple/**'

  build-and-test:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        library: ${{ fromJson(needs.changes.outputs.libraries) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install-poetry-deps
        working-directory: ${{ matrix.library }}
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with=dev --no-root

      - id: lint-flake8
        working-directory: ${{ matrix.library }}
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Generate coverage
        working-directory: ${{ matrix.library }}
        run: |
          poetry run pytest --timeout=10 --cov --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
