name: lint-api

on:
  push:
    paths:
      - 'api/**'
      - 'libs/python/**'
      - '.github/workflows/lint-api.yaml'

defaults:
  run:
    working-directory: api

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: "${{ github.workspace }}/api"

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --group dev

      - name: Run pylint
        run: |
          uv run lint
