name: publish-gcid

on:
  release:
    types: [ published ]

  workflow_dispatch: { }
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: libs/python/cryptid
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip uv
          pip install build twine
          uv lint
          uv test
          uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: libs/python/cryptid/dist/
          password: ${{ secrets.PYPI_TOKEN }}
