name: push-tagged-images
on:
  push: # only run when PR merged to main
    branches:
      - 'main'
    paths:
      - 'sites/**'
      - 'ams/**'
      - 'libs/**'
      - '.github/workflows/push-tagged-images.yaml'

  workflow_dispatch:
jobs:
  changes:
    concurrency:
      group: push-tagged-images
      cancel-in-progress: false

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    outputs:
      images: ${{ steps.post_filter.outputs.changes }}
      has_changes: ${{ steps.post_filter.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # setup all the filters to match Dockerfile locations
          filters: |
            ams/app/:
              - 'libs/python/**'
              - 'ams/app/**'
              - '.github/workflows/push-tagged-images.yaml' # always build at least one image if the workflow changes
            ams/test-worker/:
              - 'libs/python/**'
              - '.github/workflows/push-automation-images.yaml' # always build at least one image if the workflow changes
            ams/packager/:
              - 'ams/packager/**'
              - 'libs/python/**'
            ams/canary/:
              - 'ams/canary/**'
            sites/:
              - 'sites/**'
            workloads/lets-encrypt/:
              - 'ams/lets-encrypt/**'
            workloads/nginx/:
              - 'workloads/nginx/**'
            workloads/gcp/gcs-proxy/:
              - 'workloads/gcp/gcs-proxy/**'

      # Set matrix based on filter results or use all images for manual trigger
      - id: post_filter
        uses: actions/github-script@v6
        with:
          script: |
            const isManualTrigger = context.eventName === 'workflow_dispatch';
            const allImages = ["ams/app/", "workloads/nginx/", "workloads/gcp/gcs-proxy/", "workloads/lets-encrypt/", "ams/packager/", "ams/canary/", "sites/"];
            
            let changes;
            try {
              changes = JSON.parse('${{ steps.filter.outputs.changes }}');
            } catch (e) {
              changes = [];
              console.log('Error parsing changes or empty changes array:', e);
            }
            
            if (isManualTrigger) {
              // For manual trigger, use all images
              console.log('Manual trigger detected, building all images');
              core.setOutput('changes', JSON.stringify(allImages));
              core.setOutput('has_changes', 'true');
            } else {
              // For automatic trigger, use filtered changes
              const hasChanges = Array.isArray(changes) && changes.length > 0;
            
              console.log('Changes detected:', hasChanges ? 'yes' : 'no');
              core.setOutput('changes', JSON.stringify(changes));
              core.setOutput('has_changes', hasChanges ? 'true' : 'false');
            }

  build-base:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build libs-python image
        uses: docker/build-push-action@v5
        with:
          context: libs/python
          tags: libs-python:${{ github.sha }}
          load: true
      - name: Build ams-app image
        uses: docker/build-push-action@v5
        with:
          context: ams/app
          tags: ams-app:${{ github.sha }}
          load: true
          build-args: |
            LIBS_PYTHON_IMAGE=libs-python:${{ github.sha }}
      - name: Save ams-app to tar
        run: |
          docker save ams-app:${{ github.sha }} > /tmp/ams-app-${{ github.sha }}.tar
          docker save libs-python:${{ github.sha }} > /tmp/libs-python-${{ github.sha }}.tar
      - name: Upload libs-python image
        uses: actions/upload-artifact@v4
        with:
          name: libs-python-${{ github.sha }}
          path: /tmp/libs-python-${{ github.sha }}.tar
          retention-days: 1
          overwrite: true
      - name: Upload ams-app image
        uses: actions/upload-artifact@v4
        with:
          name: ams-app-${{ github.sha }}
          path: /tmp/ams-app-${{ github.sha }}.tar
          retention-days: 1
          overwrite: true

  build-tag-publish:
    runs-on: ubuntu-latest
    environment: main
    needs:
      - changes
      - build-base
    if: needs.changes.outputs.has_changes == 'true'
    permissions:
      repository-projects: read
      pull-requests: write
      id-token: write
      contents: write

    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.changes.outputs.images) }}

    env:
      IMAGE_NAME: "${{ matrix.image }}"
      NODE_ENV: "staging"
      GCR_PROJECT_ID: "296075347103"
      GCR_REPO_LOCATION: 'us-central1'
      GCR_URL: 'us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images'
      GCR_SERVICE_ACCOUNT: 'github-actions-service-account@controlnet-407314.iam.gserviceaccount.com'
      GCR_WORKLOAD_IDENTITY_PROVIDER: 'projects/296075347103/locations/global/workloadIdentityPools/gh-infra-pool/providers/github-mythica-infra'
      ECR_ROLE: 'arn:aws:iam::050752617649:role/MythicaGitHubActionPushTaggedImages'
      ECR_URL: '050752617649.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-050752617649-us-east-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          project_id: ${{ env.GCR_PROJECT_ID }}
          service_account: ${{ env.GCR_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.GCR_WORKLOAD_IDENTITY_PROVIDER }}

      - name: AWS Auth
        id: aws-auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ECR_ROLE }}
          role-session-name: github-actions-ecr
          aws-region: us-east-1

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: '${{ env.GCR_REPO_LOCATION }}-docker.pkg.dev'
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Generate tag
        id: generate_tag
        run: |
          workloads/github/tagging/get-dockerfile-tag.sh ${{ matrix.image }} >> $GITHUB_OUTPUT

      - name: Push tag
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 10
          command: |
            git tag ${{ steps.generate_tag.outputs.new_tag }}
            git push origin ${{ steps.generate_tag.outputs.new_tag }}
            echo "## Tagged image ${{ matrix.image }} as ${{ steps.generate_tag.outputs.new_tag }}" > $GITHUB_STEP_SUMMARY

      - name: Download ams-app image
        uses: actions/download-artifact@v4
        with:
          name: ams-app-${{ github.sha }}
          path: /tmp

      - name: Download libs-python base image
        uses: actions/download-artifact@v4
        with:
          name: libs-python-${{ github.sha }}
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/libs-python-${{ github.sha }}.tar
          docker load --input /tmp/ams-app-${{ github.sha }}.tar

      - name: Build and push ${{ matrix.image }}
        id: build_push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          tags: |
            ${{ env.GCR_URL }}/${{ steps.generate_tag.outputs.image_name }}:${{ steps.generate_tag.outputs.new_tag_version }}
            ${{ env.ECR_URL }}/${{ steps.generate_tag.outputs.image_name }}:${{ steps.generate_tag.outputs.new_tag_version }}
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            LIBS_PYTHON_IMAGE=libs-python:${{ github.sha }}
            AMS_APP_IMAGE=ams-app:${{ github.sha }}
          load: true

      - name: Send Discord notification
        if: always()
        run: |
          echo "{ \"content\": \"" > message.json
          echo "${{ github.event.pull_request.title }}\n" >> message.json
          echo "IMAGE=${{ steps.generate_tag.outputs.image_name }}:${{ steps.generate_tag.outputs.new_tag_version }}\n" >> message.json
          echo IMAGE=${{ steps.generate_tag.outputs.image_name }}:${{ steps.generate_tag.outputs.new_tag_version }} >> $GITHUB_ENV
          if [ "${{ steps.build_push.outcome }}" == "failure" ]; then
              echo "❌ $IMAGE build failed, see: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> message.json
          else
              echo "✅ $IMAGE is now available for testing at https://api-staging.mythica.gg" >> message.json
          fi
          echo "\" }" >> message.json
          curl -X POST ${{ secrets.DISCORD_INFRA_NOTIFICATIONS_WEBOOK }} \
               -H "Content-Type: application/json" \
               --data @message.json
