name: sites-awful-ui-code-quality

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'sites/awful-ui/**'
      - '.github/workflows/sites-awful-ui-code-quality.yaml'

  push:
    branches:
      - '**'
    paths:
      - 'sites/awful-ui/**'
      - '.github/workflows/sites-awful-ui-code-quality.yaml'

defaults:
  run:
    working-directory: sites/awful-ui

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: sites/awful-ui/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: sites/awful-ui/pnpm-lock.yaml
      - name: install dependencies
        run: pnpm install
      - run: pnpm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: docker/build-push-action@v5
        with:
          context: sites/awful-ui
          tags: test

