name: sites/jungle3 Publish QA

on:
  push:
    paths:
      - 'sites/jungle3/**'

defaults:
  run:
    working-directory: .

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    env:
      NODE_ENV: "production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: |
          . ./env.sh
          invoke docker-deploy --image sites/jungle3
        
