name: sites/jungle3 Publish QA

on:
  push:
    paths:
      - 'sites/jungle3/**'
      - '.github/workflows/sites-jungle3-publish-qa.yaml'

defaults:
  run:
    working-directory: .

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: read
      pull-requests: write
      id-token: write

    env:
      NODE_ENV: "production"
      AR_REPO_LOCATION: 'us-central1'
      AR_URL: 'us-central1-docker.pkg.dev/controlnet-407314/gke-us-central1-images'
      SERVICE_ACCOUNT: 'github-actions-service-account@controlnet-407314.iam.gserviceaccount.com'
      WORKLOAD_IDENTITY_PROVIDER: 'projects/296075347103/locations/global/workloadIdentityPools/gh-infra-pool/providers/github-mythica-infra'
    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: sites/jungle3
          tags: mythica-sites-jungle3-dist:latest
        
