apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
  annotations:
    config-update: "2024-11-12"
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:55681"

      # Data sources: metrics
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 5s
              static_configs:
                - targets: [localhost:8888]

    exporters:
      otlp:
        endpoint: ingest.us.signoz.cloud:443
        tls:
          insecure: false
        timeout: 30s
        headers:
          "signoz-access-token": ${SIGNOZ_API_KEY}

    processors:
      batch:
        timeout: 5s
        send_batch_size: 512
        send_batch_max_size: 10000

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlp]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
