# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
namespace: "api-staging"
tier: "web"
release: "staging"  # note that helm release is mapped to MYTHICA_ENVIRONMENT in k8s deployments
hostnameDecorator: "-staging"
domains:
  - oss-staging.mythica.gg
  - api-staging.mythica.gg
  - dex-staging.mythica.gg
  - oss-staging.mythica.ai
  - api-staging.mythica.ai
  - dex-staging.mythica.ai
serviceAccount:
  secretName: front-end-api-staging-sa
  email: front-end-api-staging-sa@controlnet-407314.iam.gserviceaccount.com

apiBaseUrl: https://api-staging.mythica.ai/v1
imagesBaseUrl: https://api-staging.mythica.ai/images
sceneTalkUrl: "wss://scenetalk.mythica.gg/staging/"

auth0:
  domain: dev-dtvqj0iuc5rnb6x2.us.auth0.com
  clientId: ddxXLUYxqXMKCv6VZ7zWLly4B19NvDoW
  audience: https://api-staging.mythica.ai/v1
  redirectUrl: https://api-staging.mythica.ai

api:
  app:
    replicas: 2
    maxUnavailable: 1
    maxSurge: 2
    base_url: "https://api-staging.mythica.ai/v1"
    telemetry_endpoint: "http://otel-collector.default:4317"
    nodeSelector: spot
    terminationGracePeriodSeconds: 15
  gcsProxy:
    replicas: 2
    maxUnavailable: 1
    maxSurge: 4
    nodeSelector: spot
    terminationGracePeriodSeconds: 15
  letsEncrypt:
    secretName: mythica-lets-encrypt-staging-tls
    replicas: 1
    maxUnavailable: 1
    maxSurge: 2
    nodeSelector: scale-out
    terminationGracePeriodSeconds: 60
  packager:
    replicas: 1
    maxUnavailable: 1
    maxSurge: 2
    nodeSelector: spot
    terminationGracePeriodSeconds: 15
  webFront:
    replicas: 2
    maxUnavailable: 1
    maxSurge: 5
    nginxConfig: "nginx-gke-staging.conf"
    nodeSelector: spot
    terminationGracePeriodSeconds: 15
  canary:
    name: "canary"
    replicas: 1
    maxUnavailable: 0
    maxSurge: 2
    telemetry_endpoint: "http://otel-collector.default:4317"
    nodeSelector: spot
    terminationGracePeriodSeconds: 15
